version: '3'
services:
  web:
    container_name: ${WEB_HOST}
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: remote_host=172.17.0.1
      REDIS_URL: ${REDIS_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"